// <auto-generated />
using System;
using INFC20P1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INFC20P1.Migrations
{
    [DbContext(typeof(INFC20P1TransactionContext))]
    [Migration("20221015141714_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("INFC20P1.Models.Transaction", b =>
                {
                    b.Property<int>("tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("tid"), 1L, 1);

                    b.Property<int>("recieve_id")
                        .HasColumnType("int");

                    b.Property<int>("send_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("t_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("tname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tid");

                    b.ToTable("Transaction");
                });
#pragma warning restore 612, 618
        }
    }
}
